config:
  backup: true
  banner: true
  create: true
  dotpath: .
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_neomuttrc:
    src: config/neomutt/neomuttrc
    dst: ~/.config/neomutt/neomuttrc
  f_glenn:
    src: config/neomutt/glenn
    dst: ~/.config/neomutt/glenn
  f_dracula.muttrc:
    src: config/neomutt/dracula.muttrc
    dst: ~/.config/neomutt/dracula.muttrc
  f_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
  f_plugins.vim:
    src: config/nvim/vim-plug/plugins.vim
    dst: ~/.config/nvim/vim-plug/plugins.vim
  f_settings.vim:
    src: config/nvim/general/settings.vim
    dst: ~/.config/nvim/general/settings.vim
  f_keyboard.vim:
    src: config/nvim/general/keyboard.vim
    dst: ~/.config/nvim/general/keyboard.vim
  f_dogrun.vim:
    src: config/nvim/themes/dogrun.vim
    dst: ~/.config/nvim/themes/dogrun.vim
  f_coc.vim:
    src: config/nvim/plug-config/coc.vim
    dst: ~/.config/nvim/plug-config/coc.vim
  f_airline.vim:
    src: config/nvim/themes/airline.vim
    dst: ~/.config/nvim/themes/airline.vim
  f_signify.vim:
    src: config/nvim/plug-config/signify.vim
    dst: ~/.config/nvim/plug-config/signify.vim
  f_nerdtree.vim:
    src: config/nvim/plug-config/nerdtree.vim
    dst: ~/.config/nvim/plug-config/nerdtree.vim
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
    chmod: '644'
  f_bat.zsh:
    src: oh-my-zsh/custom/bat.zsh
    dst: ~/.oh-my-zsh/custom/bat.zsh
  f_bin.zsh:
    src: oh-my-zsh/custom/bin.zsh
    dst: ~/.oh-my-zsh/custom/bin.zsh
  f_dotdrop.zsh:
    src: oh-my-zsh/custom/dotdrop.zsh
    dst: ~/.oh-my-zsh/custom/dotdrop.zsh
  f_golang.zsh:
    src: oh-my-zsh/custom/golang.zsh
    dst: ~/.oh-my-zsh/custom/golang.zsh
  f_kubectl.zsh:
    src: oh-my-zsh/custom/kubectl.zsh
    dst: ~/.oh-my-zsh/custom/kubectl.zsh
  f_mail.zsh:
    src: oh-my-zsh/custom/mail.zsh
    dst: ~/.oh-my-zsh/custom/mail.zsh
  f_path.zsh:
    src: oh-my-zsh/custom/path.zsh
    dst: ~/.oh-my-zsh/custom/path.zsh
  f_terraform.zsh:
    src: oh-my-zsh/custom/terraform.zsh
    dst: ~/.oh-my-zsh/custom/terraform.zsh
  f_plug.vim:
    src: config/nvim/autoload/plug.vim
    dst: ~/.config/nvim/autoload/plug.vim
  f_onedark.vim:
    src: config/nvim/themes/onedark.vim
    dst: ~/.config/nvim/themes/onedark.vim
profiles:
  gondor:
    dotfiles:
    - f_neomuttrc
    - f_glenn
    - f_dracula.muttrc
    - f_init.vim
    - f_plugins.vim
    - f_settings.vim
    - f_keyboard.vim
    - f_dogrun.vim
    - f_coc.vim
    - f_airline.vim
    - f_signify.vim
    - f_nerdtree.vim
    - f_tmux.conf
    - f_zshrc
    - f_bat.zsh
    - f_bin.zsh
    - f_dotdrop.zsh
    - f_golang.zsh
    - f_kubectl.zsh
    - f_mail.zsh
    - f_path.zsh
    - f_terraform.zsh
    - f_plug.vim
    - f_onedark.vim
